spring.application.name=url-shortner
# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener_db
spring.datasource.username=root
spring.datasource.password=Rishi@12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.data.redis.host=localhost
spring.data.redis.port=6379
jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long
jwt.expiration=86400000
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rishithayellanki12@gmail.com
spring.mail.password=fmqr aayq ztte ctvs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Frontend URL (for reset link)
app.frontend.url=http://localhost:3000